# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: niriblue
description: Custom niri image built on Fedora Atomic base

base-image: quay.io/fedora-ostree-desktops/base-atomic
image-version: 44

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - scottames/ghostty
        - dejan/lazygit
        - peterwu/rendezvous
        - ublue-os/packages
      files:
        - https://negativo17.org/repos/fedora-multimedia.repo
    install:
      packages:
        - alacritty
        - bibata-cursor-themes
        - cosmic-files
        - cosmic-settings
        - fd-find
        - ghostty
        - grim
        - jetbrains-mono-fonts-all
        - lazygit
        - neovim
        - noctalia
        - pamixer
        - podman-compose
        - slurp
        - starship
        - tealdeer
        - niri
        - xwayland-satellite
        - mate-polkit
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-gnome
        - sddm
        - sddm-themes
        - qt5-qtgraphicaleffects
        - qt5-qtquickcontrols2
        - qt5-qtsvg
        - kwallet
        - pam-kwallet
        - pipewire
        - wireplumber
        - pipewire-pulseaudio
        - bluez
        - default-fonts-core-sans
        - google-noto-emoji-fonts
        - ffmpeg
        - libva-utils
        - gamemode
        - mangohud
        - gamescope
        - ublue-os-udev-rules
        - ublue-os-luks
        - tpm2-tools
        - uupd
        - gnome-keyring-pam
        - code
        - qemu-kvm
        - libvirt
        - virt-manager
        - virt-install
        - edk2-ovmf
        - swtpm
        - ublue-os-libvirt-workarounds

  - type: dnf
    remove:
      packages:
        - waybar

  - type: containerfile
    snippets:
      - COPY --from=ghcr.io/ublue-os/akmods:ogc-44@sha256:de4625d6e43962231c879bb7bee849202af99db402b81f7e48241815f5b9d550 /rpms /tmp/rpms
      - COPY --from=ghcr.io/ublue-os/akmods:ogc-44@sha256:de4625d6e43962231c879bb7bee849202af99db402b81f7e48241815f5b9d550 /kernel-rpms /tmp/rpms/kernel
      - RUN dnf install -y /tmp/rpms/ublue-os/ublue-os-akmods-addons*.rpm

  - type: script
    scripts:
      - install-ogc-kernel.sh

  - type: containerfile
    snippets:
      - RUN dnf install -y /tmp/rpms/kmods/kmod-xone*.rpm && rm -rf /tmp/rpms
      - COPY --from=ghcr.io/ublue-os/akmods-extra:ogc-44@sha256:3f670662f8a2a55a3b1963c45e2fd0fa31c27d5d9ca0cec087dc116dfc468e02 /rpms /tmp/extra-rpms
      - RUN dnf install -y /tmp/extra-rpms/kmods/kmod-ryzen_smu*.rpm /tmp/extra-rpms/extra/ryzen_smu-0*.rpm && rm -rf /tmp/extra-rpms

  - type: script
    scripts:
      - noctalia-default.sh
      - sddm-theming.sh
      - regenerate-initramfs.sh

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - com.valvesoftware.Steam

  - type: systemd
    system:
      enabled:
        - sddm.service
        - sddm-boot.service
        - uupd.timer
    user:
      enabled:
        - podman.socket

  - type: containerfile
    snippets:
      - RUN bootc container lint

  - type: signing
